version: '3.8'

services:
  app:
    user: "1000"
    image: ghcr.io/josepostiga/syllabus/php:dev

  mailhog:
    image: mailhog/mailhog:v1.0.1
    expose:
      - 1025
    ports:
      - "8025:8025"
    volumes:
      - mailhog_data:/maildir
    environment:
      MH_STORAGE: maildir
    restart: unless-stopped
    networks:
      - syllabus

  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: syllabus
    restart: unless-stopped
    networks:
      - syllabus

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - syllabus

  web-server:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syllabus.entrypoints=http"
      - "traefik.http.routers.syllabus.rule=HostRegexp(`getsyllabus.test`, `{subdomain:[\\S]+}.getsyllabus.test`)"
    image: caddy:2-alpine
    expose:
      - 80
      - 443
    volumes:
      - ./.docker/server/Caddyfile:/etc/caddy/Caddyfile:ro
      - .:/var/www/html:delegated
    restart: unless-stopped
    networks:
      - web
      - syllabus

volumes:
  mailhog_data:
  postgres_data:

networks:
  web:
    external: true
